### ISSUE TITLE
Algorithm misidentification

### ISSUE THREAD

**Issue by mtcolman** [Santandersecurityresearch/cryptobom-forge#4]
Hi, I'm using an `output.sarif` file with both md5 and sha1 results in it.
```
    "results" : [ {
      "ruleId" : "py/quantum-readiness/cbom/all-cryptographic-algorithms",
      "ruleIndex" : 1,
      "rule" : {
        "id" : "py/quantum-readiness/cbom/all-cryptographic-algorithms",
        "index" : 1
      },
      "message" : {
        "text" : "Use of algorithm MD5"
      },
      "locations" : [ {
        "physicalLocation" : {
          "artifactLocation" : {
            "uri" : "sqli/dao/dummy.py",
            "uriBaseId" : "%SRCROOT%",
            "index" : 0
          },
          "region" : {
            "startLine" : 1,
            "startColumn" : 21,
            "endColumn" : 24
          },
          "contextRegion" : {
            "startLine" : 1,
            "endLine" : 3,
            "snippet" : {
              "text" : "from hashlib import md5\r\nfrom hashlib import sha1\r\nfrom typing import NamedTuple, Optional\r\n"
            }
          }
        }
      } ],
      "partialFingerprints" : {
        "primaryLocationLineHash" : "a3859dd903b217e8:1",
        "primaryLocationStartColumnFingerprint" : "20"
      }
    }, {
      "ruleId" : "py/quantum-readiness/cbom/all-cryptographic-algorithms",
      "ruleIndex" : 1,
      "rule" : {
        "id" : "py/quantum-readiness/cbom/all-cryptographic-algorithms",
        "index" : 1
      },
      "message" : {
        "text" : "Use of algorithm SHA1"
      },
      "locations" : [ {
        "physicalLocation" : {
          "artifactLocation" : {
            "uri" : "sqli/dao/dummy.py",
            "uriBaseId" : "%SRCROOT%",
            "index" : 0
          },
          "region" : {
            "startLine" : 2,
            "startColumn" : 21,
            "endColumn" : 25
          },
          "contextRegion" : {
            "startLine" : 1,
            "endLine" : 4,
            "snippet" : {
              "text" : "from hashlib import md5\r\nfrom hashlib import sha1\r\nfrom typing import NamedTuple, Optional\r\n\r\n"
            }
          }
        }
      } ],
```

However I can see that the snippet which is being provided for both is:
```
"snippet" : {
  "text" : "from hashlib import md5\r\nfrom hashlib import sha1\r\nfrom typing import NamedTuple, Optional\r\n\r\n"
```

This means that when `utils.py` performs:
```
def get_algorithm(code_snippet):
    match = _ALGORITHM_REGEX.search(code_snippet)
    if match:
        return match.group()
    return 'unknown'
```

The match is "MD5" on both occasions.

**MD5 was the finding, MD5 detected as algorithm**
![image](https://github.com/Santandersecurityresearch/cryptobom-forge/assets/33348891/508cb2b6-bfd3-41b8-a45f-cdd752507048)

**SHA1 was the finding, MD5 detected as algorithm**
![image](https://github.com/Santandersecurityresearch/cryptobom-forge/assets/33348891/b41fd982-537b-4d9c-b069-dbed6f8b2a0b)

The actual code in the script is:
```
from hashlib import md5
from hashlib import sha1
from typing import NamedTuple, Optional

from aiopg import Connection
...
...
```

I shall look look into whether the snippet can be less verbose,

> [--[no-]sarif-add-snippets](https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/database-analyze#--no-sarif-add-snippets)
> 
> [SARIF formats only] Include code snippets for each location mentioned in the results, with two lines of context before and after the reported location.  

(https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/database-analyze#--no-sarif-add-snippets)

Because at the moment this can cause a problem for the `match = _ALGORITHM_REGEX.search(code_snippet)` because `re.search` just finds the first match (vs `.findall` which will return a list of all non-overlapping matches in the input string).

So with this particular code, when the cbom and cryptocheck are generated, I'm only ever getting the MD5 finding.

**Comment by mtcolman** [comment]
I've amended my local instance of `main.py` to do the following:
```
def _read_file(query_file, application_name=None, exclusion_pattern=None):
    with open(query_file) as query_output:
        query_output = json.load(query_output)['runs'][0]
        
        ### start of new code ###
        for result in query_output['results']:
          snippet = result['locations'][0]['physicalLocation']['contextRegion']['snippet']['text']
          lineStart = result['locations'][0]['physicalLocation']['region']['startLine']
          snippetStart = result['locations'][0]['physicalLocation']['contextRegion']['startLine']

          # Check if '\r\n' is present in the snippet before splitting
          if '\r\n' in snippet:
            actualLine = ""
            array_of_lines = []
            # Split the code snippet at instances of '\r\n' and handle consecutive newlines
            array_of_lines = [line.strip() for line in snippet.split('\r\n')]
            actualLine = array_of_lines[lineStart - 1]

            # Update the snippet record in query_output
            result['locations'][0]['physicalLocation']['contextRegion']['snippet']['text'] = actualLine
            ### end of new code ###
```

And this now handles it correctly. Would this be acceptable?

**Comment by emilejq** [comment]
Hi,

Thanks for raising this.

I see two options:

1. Use a hybrid approach in which the algorithm is first extracted from the message text and checked against the list of pre-defined algorithms in the `library.yml` file. If it doesn't match a known algorithm (as the queries [currently](https://github.com/github/codeql/blob/main/python/ql/src/experimental/cryptography/inventory/new_models/BlockModeAlgorithms.ql) also report block modes and padding schemes as algorithms in the message text), then it can be inferred from the code snippet using the current logic

2. Extract a precise code snippet using the location information provided in region object and extract the algorithm from this reduced code snippet

I agree that the latter is the better choice as using the message text would be brittle, but I can see a few problems with the way you've implemented it above:

- It wouldn't handle regions that are spread over multiple lines. For instance:

```json
"region": {
    "startLine": 183,
    "startColumn": 33,
    "endLine": 185,
    "endColumn": 18
}
```

- It doesn't take in to account information about the start and end columns and so the same parsing issue would occur if multiple algorithms appear in the same line
- Replacing the snippet in the query output with the reduced snippet loses contextual information that is needed later on
- `array_of_lines[lineStart - 1]` only works in this case because the findings are at the start of the file. If the start line is somewhere in the middle of the file, line 183 for instance, it would throw an `IndexError`
- `'\r\n'` is Windows specific and not guaranteed to be the new line sequence in all the outputs. It would be better to split it just on `'\n'`

The `--sarif-add-snippets` option adds two lines of context either side, so generally it would be sufficient to take the start line to be the third element of the split output, but it needs to handle special cases where the start line is one of the first two lines of the file

**Comment by mtcolman** [comment]
Hi @emilejq thanks for the feedback. I've modified the code to overcome some of the shortfalls you mentioned:

- it now uses the "snippet start minus finding start" to get the value of item to lookup in the list.
- it checks if `\r\n` is present to cover Windows use cases, if not it looks for `\n` for the Linux use cases
- it creates a new key `...['snippet']['exactText']` for use in the algorithm lookup, leaving the `...['snippet']['text']` unedited for other lookups (in `algorithm.py`)
- I've added in the start and end columns to get the precise text (though this won't cope with multi-line finding at the moment)

Think this just leaves the multi-line finding to be dealt with. I'm not sure I have an example of this, do you have a suggestion?

**Comment by mtcolman** [comment]
Handling multi-line, along with start and end col across mutliple lines has now been coded - so I think I've covered all the items you previously mentioned @emilejq.

**Comment by emilejq** [comment]
Apologies for the delay in replying on this.

Thanks for making these changes. I'd rather not edit the CodeQL dict, even if it is keeping all the edits in a new key. I think this would be better as a utility method in `parser/utils.py`, something like `extract_precise_snippet` that returns the reduced code snippet.

And a couple more issues to fix:

* The key `startColumn` is not included in the `region` object if the start value is 1. See (https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/sarif-output#region-object). If this is the case, the code would throw a `KeyError`. On line 64 you should use `.get('startColumn', 1)`

* On line 73 you are removing leading whitespace from all lines, but this will cause the start column index to be misaligned with the string. On lines 76/81 where you take the substring from the start column index, this will end up incorrectly slicing some code off the start if the line previously had leading whitespace

Thanks

**Comment by mtcolman** [comment]
Thanks @emilejq. I've updated the code to address the two comments. Happy to move it from `main.py` to `parser/utils.py`. Would you want it called from here:

**algorithm.py**
```
def _generate_crypto_component(codeql_result):
    code_snippet = utils.extract_precise_snippet(codeql_result)
    algorithm = utils.get_algorithm(code_snippet)

    code_snippet = codeql_result['locations'][0]['physicalLocation']['contextRegion']['snippet']['text']
    ...
```

**utils/parser.py**
```
def extract_precise_snippet(code_snippet):
    snippet = code_snippet['locations'][0]['physicalLocation']['contextRegion']['snippet']['text']
    snippet_start = code_snippet['locations'][0]['physicalLocation']['contextRegion']['startLine']
    line_start = code_snippet['locations'][0]['physicalLocation']['region']['startLine']
    line_end = code_snippet['locations'][0]['physicalLocation']['region'].get('endLine', None)
    line_start_col = code_snippet['locations'][0]['physicalLocation']['region'].get('startColumn', 1)
    line_end_col = code_snippet['locations'][0]['physicalLocation']['region']['endColumn']

    # Check if '\r\n' or '\n' is present in the snippet before splitting
    split_value = '\r\n' if '\r\n' in snippet else '\n' if '\n' in snippet else None
      
    if split_value:
        start_line_index  = line_start - snippet_start
        # Split the code snippet at instances of '\r\n' or '\n' and handle consecutive newlines
        array_of_lines = [line for line in snippet.split(split_value)]
        if line_end is None or (line_start == line_end):
            actual_line = array_of_lines[start_line_index]
            precise_snippet = actual_line[line_start_col - 1:line_end_col]
        else:
            end_line_index = start_line_index + (line_end - line_start)
            actual_lines = array_of_lines[start_line_index:end_line_index + 1]
            # Adjust the first and last lines to only include the necessary columns
            actual_lines[0] = actual_lines[0][line_start_col - 1:]
            actual_lines[-1] = actual_lines[-1][:line_end_col]
            precise_snippet = split_value.join(actual_lines)

        # Provide the precise snippet text back
        return precise_snippet
    
    else:
        return code_snippet['locations'][0]['physicalLocation']['contextRegion']['snippet']['text']
```

Cheers.

**Comment by emilejq** [comment]
Thanks for making those changes. I'm happy that this now works as it should functionally.

I've added a review to the PR with suggestions around simplifying the code and keeping it consistent with the coding style used elsewhere in the repo.

Could you check that?

Thanks

**Comment by mtcolman** [comment]
@emilejq thanks for the feedback. I believe all requested/suggested changes have been implemented.
